import type { Metadata } from 'next';
import QueryProvider from '@/shared/providers/QueryProvider';
import './globals.css';
import Header from '@/shared/ui/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className='h-full antialiased'>
      <body className='flex min-h-full flex-col overflow-x-hidden px-4'>
        <Header />
        <div className='mx-auto w-full max-w-[1200px]'>
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
